services:
  - type: web
    name: crystal-parking-bot
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/chromium
      - key: PYTHONUNBUFFERED
        value: 1
